/*
 * rcc.h
 *
 *  Created on: Jan 31, 2023
 *      Author: Jakob
 */

#ifndef RCC_H_
#define RCC_H_

#include "stm32l476g.h"

#define RCC_APB1ENR1_USART2			(1 << 17)
#define RCC_APB1ENR1_LCD			(1 << 9)
#define RCC_APB1ENR1_SPI2			(1 << 14)
#define RCC_APB1ENR1_SPI3			(1 << 15)
#define RCC_APB2ENR_SPI1			(1 << 12)

#define RCC_AHB2ENR_GPIOA			(1 << 0)
#define RCC_AHB2ENR_GPIOB			(1 << 1)
#define RCC_AHB2ENR_GPIOC			(1 << 2)
#define RCC_AHB2ENR_GPIOD			(1 << 3)
#define RCC_AHB2ENR_GPIOE			(1 << 4)
#define RCC_AHB2ENR_GPIOF			(1 << 5)
#define RCC_AHB2ENR_GPIOG			(1 << 6)
#define RCC_AHB2ENR_GPIOH			(1 << 7)
#define RCC_AHB2ENR_GPIOI			(1 << 8)

#define RCC_GPIOA_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOA
#define RCC_GPIOB_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOB
#define RCC_GPIOC_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOC
#define RCC_GPIOD_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOD
#define RCC_GPIOE_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOE
#define RCC_GPIOF_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOF
#define RCC_GPIOG_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOG
#define RCC_GPIOH_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOH
#define RCC_GPIOI_CLK_ENABLE()		RCC->AHB2ENR |= RCC_AHB2ENR_GPIOI

#define RCC_LCD_CLK_ENABLE()		RCC->APB1ENR1 |= RCC_APB1ENR1_LCD
#define RCC_USART2_CLK_ENABLE()		RCC->APB1ENR1 |= RCC_APB1ENR1_USART2
#define RCC_SPI2_CLK_ENABLE()		RCC->APB1ENR1 |= RCC_APB1ENR1_SPI2
#define RCC_SPI3_CLK_ENABLE()		RCC->APB1ENR1 |= RCC_APB1ENR1_SPI3
#define RCC_SPI1_CLK_ENABLE()		RCC->APB2ENR |= RCC_APB2ENR_SPI1

#define RCC_GPIOA_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOA
#define RCC_GPIOB_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOB
#define RCC_GPIOC_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOC
#define RCC_GPIOD_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOD
#define RCC_GPIOE_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOE
#define RCC_GPIOF_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOF
#define RCC_GPIOG_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOG
#define RCC_GPIOH_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOH
#define RCC_GPIOI_CLK_DISABLE()		RCC->AHB2ENR &= ~RCC_AHB2ENR_GPIOI

#define RCC_LCD_CLK_DISABLE()		RCC->APB1ENR1 &= ~RCC_APB1ENR1_LCD
#define RCC_USART2_CLK_DISABLE()	RCC->APB1ENR1 &= ~RCC_APB1ENR1_USART2
#define RCC_SPI2_CLK_DISABLE()		RCC->APB1ENR1 &= ~RCC_APB1ENR1_SPI2
#define RCC_SPI3_CLK_DISABLE()		RCC->APB1ENR1 &= ~RCC_APB1ENR1_SPI3
#define RCC_SPI1_CLK_DISABLE()		RCC->APB2ENR &= ~RCC_APB2ENR_SPI1

#endif /* RCC_H_ */
