/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32l476g.h"
#include "systick.h"
#include "joystick.h"
#include "led.h"
#include "usart.h"
#include "lcd.h"
#include "spi.h"
#include "gyro.h"

int main(void)
{
	stm32l476g_init();
	SPI_InitTypeDef spi_init = L3GD20_SPI_INIT;
	spi2_init(&spi_init);



	gyro_init();

	float xyz[3];
	int temp;
	char str_temp[6];
	char str_xyz[50];
	for(;;) {
		l3gd20_read_xyz(xyz);

		sprintf(str_xyz, "X: %f Y: %f Z: %f\n\r", xyz[0], xyz[1], xyz[2]);
		usart2_send_string(str_xyz);

		temp = l3gd20_read_temp();
		sprintf(str_temp, "%d\n\r", temp);
		lcd_display_string(str_temp);
		stk_wait_ms(50);
	}


	for(;;);
}
