/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476g.h"
#include "systick.h"
#include "joystick.h"
#include "led.h"
#include "usart.h"
#include "lcd.h"
#include "spi.h"
#include "l3gd20.h"

int main(void)
{
	stm32l476g_init();
	SPI_InitTypeDef init = L3GD20_SPI_INIT;
	spi2_init(&init);

	l3gd20_init();
	L3GD20_CS_LOW();

	uint8_t id = l3gd20_read(L3GD20_WHO_AM_I);

	L3GD20_CS_HIGH();
	for(;;);
}
